name: base_structure
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.15+16

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  bloc: ^6.1.1
  flutter_bloc: ^6.1.1
  equatable:
  auto_route: ^0.6.9
  easy_localization: ^2.3.3
  flutter_local_notifications: ^3.0.2
  image_picker: ^0.6.7+17
  shared_preferences: ^0.5.12+4
  flutter_launcher_icons: ^0.8.1
  url_launcher: ^5.7.10
  firebase_messaging: ^7.0.3
  flutter_staggered_animations: ^0.1.2
  location: ^2.3.5
  cached_network_image: ^2.5.0
  http_parser: ^3.1.4
  flutter_rating_bar: ^3.2.0+1
  bot_toast: ^3.0.5
  flutter_easyloading: ^2.2.2
  flutter_phoenix: ^0.1.0
  badges: ^1.1.6
  google_fonts: ^1.1.2
  flutter_swiper: ^1.1.6
  dio_http_cache: ^0.2.11
  modal_bottom_sheet: ^1.0.0+1
  dropdown_search: ^0.4.8
  flutter_typeahead: ^2.0.0
  flutter_absolute_path: ^1.0.6
  share: ^0.6.5+4
  path_provider: ^1.6.27
  dots_indicator: ^1.2.0
  geolocator: ^5.3.1
  google_maps_flutter: ^1.1.1
  flutter_html: ^1.1.1
  json_serializable: ^3.5.1
  json_annotation: ^3.1.1
  country_calling_code_picker: ^1.0.8+1
  flutter_rounded_date_picker: ^1.0.5+1
  flutter_datetime_picker: ^1.5.0
  month_picker_dialog: ^0.3.3
  file_picker: ^2.1.5+1
  infinite_scroll_pagination: ^2.3.0
  background_locator: ^1.4.0+1
  location_permissions:
  onesignal_flutter: ^2.6.3
  audioplayers: ^0.17.3
  flutter_one_signal: ^0.2.1
  whatsapp_unilink: ^1.0.0+1
  quiver: ^2.1.5
  app_settings: ^4.0.4
  flutter_image_compress: any
  permission_handler:




dev_dependencies:

  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator: ^0.6.10

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/luncherIcon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/alert.wav
    - assets/images/contactUs.png
    - assets/images/contactUsMobile.png
    - assets/images/contactWhatsApp.png
    - assets/images/following.png
    - assets/images/hands.png
    - assets/images/header.png
    - assets/images/icon.png
    - assets/images/location.png
    - assets/images/logo.png
    - assets/images/logout.png
    - assets/images/logoWhite.png
    - assets/images/luncherIcon.png
    - assets/images/menu.png
    - assets/images/nodata.png
    - assets/images/noOrders.png
    - assets/images/notification.png
    - assets/images/order.png
    - assets/images/personInfo.png
    - assets/images/place.png
    - assets/images/placeholder.png
    - assets/images/plus.png
    - assets/images/removeBlack.png
    - assets/images/removeRed.png
    - assets/images/splash.png
    - assets/images/success.png
    - assets/images/translation.png
    - assets/images/wallet.png
    - assets/images/map.png
    - assets/images/whats.png
    - assets/langs/ar-EG.json
    - assets/langs/en-US.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
