import 'package:auto_route/auto_route.dart';
import 'package:base_structure/driver/drawer/widgets/DrawerWidgetsImports.dart';
import 'package:base_structure/driver/repository/DriverRepository.dart';
import 'package:base_structure/driver/screens/home/HomeImports.dart';
import 'package:base_structure/general/blocs/generic_cubit/generic_cubit.dart';
import 'package:base_structure/general/blocs/user_cubit/user_cubit.dart';
import 'package:base_structure/general/constants/MyColors.dart';
import 'package:base_structure/general/resources/GeneralRepository.dart';
import 'package:base_structure/general/utilities/routers/Router.gr.dart';
import 'package:base_structure/general/widgets/DefaultButton.dart';
import 'package:base_structure/general/widgets/MyText.dart';
import 'package:base_structure/res.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

part 'DrawerData.dart';
part 'DriverDrawer.dart';
